
services:

  db:
    image: postgres:15.2
    container_name: best_travel
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=best_travel
      - POSTGRES_USER=ricardo
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"